version: '3.6'
services:
  # MongoDB Replica Set
  mongo1:
    image: mongo:4.2
    container_name: mongo1
    command: --replSet rs0 --bind_ip_all
    volumes:
      - rs1:/data/db
    networks:
      - mongonet
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
  mongo2:
    image: mongo:4.2
    container_name: mongo2
    command: --replSet rs0 --bind_ip_all
    volumes:
      - rs2:/data/db
    networks:
      - mongonet
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: always
  mongo3:
    image: mongo:4.2
    container_name: mongo3
    command: --replSet rs0 --bind_ip_all
    volumes:
      - rs3:/data/db
    networks:
      - mongonet
    expose:
      - 27017
    ports:
      - 27020:27017
    restart: always

networks:
  mongonet:
    attachable: true

volumes:
  rs1:
  rs2:
  rs3:
